[project]
name = "beyond-manual-marking"
version = "0.1.0"
description = "AI-driven examination evaluation system"
requires-python = ">=3.12,<3.13"

dependencies = [
    "fastapi[standard]",
    "sqlalchemy",
    "pymysql",
    "python-dotenv",
    "python-jose[cryptography]",
    "bcrypt",
    "google-genai",
    "python-multipart",
    "pymupdf",
    "python-docx"
]

[tool.fastapi]
entrypoint = "main:app"
